import type { Metadata } from "next";
import { CheckCircle2, FileSearch2, Layers3, ShieldCheck } from "lucide-react";
import Container from "@/app/components/ui/Container";
import ProposalForm from "@/app/components/growth/ProposalForm";

export const metadata: Metadata = { title: "Request a Scoped Project Proposal", description: "Request a GeekyAce proposal built around a reviewed brief, stated assumptions, delivery phases, and the right expert squad.", alternates: { canonical: "/proposal" } };

export default async function ProposalPage({ searchParams }: { searchParams: Promise<{ service?: string; expert?: string }> }) {
  const { service = "", expert = "" } = await searchParams;
  return <main className="bg-slate-50"><section className="premium-noise relative overflow-hidden bg-[#07110c] py-20 text-white sm:py-24"><div aria-hidden="true" className="premium-grid absolute inset-0 opacity-60" /><Container><div className="relative mx-auto max-w-4xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-green-300/20 bg-green-300/10 px-5 py-2 text-xs font-black uppercase tracking-[.2em] text-green-300"><FileSearch2 className="h-4 w-4" />Scope before price</span><h1 className="text-balance mt-7 text-5xl font-black leading-[.98] tracking-[-.05em] sm:text-6xl lg:text-7xl">A serious proposal starts with the right questions.</h1><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-slate-300">Share the business context, service interest, timing, and investment range. We will review the dependencies before proposing team, phases, assumptions, and cost.</p></div></Container></section><section className="py-16 sm:py-20"><Container><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><aside className="space-y-5 lg:sticky lg:top-24 lg:h-fit"><div className="rounded-[1.75rem] bg-[#07110c] p-7 text-white"><h2 className="text-2xl font-black">What a useful proposal includes</h2><ul className="mt-6 space-y-4">{["Outcome, scope, and exclusions", "Recommended roles and ownership", "Delivery phases and acceptance points", "Assumptions, timing, and commercial model"].map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-slate-300"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-green-400" />{item}</li>)}</ul></div><div className="rounded-[1.75rem] border border-slate-200 bg-white p-7"><Layers3 className="h-6 w-6 text-green-700" /><h2 className="mt-4 font-black text-slate-950">Cross-studio when needed.</h2><p className="mt-2 text-sm leading-6 text-slate-600">The proposed squad may combine technology, creative, growth, video, and operations specialists under one accountable plan.</p></div><div className="rounded-[1.75rem] border border-green-200 bg-green-50 p-7"><ShieldCheck className="h-6 w-6 text-green-700" /><h2 className="mt-4 font-black text-slate-950">No delivery guarantee before discovery.</h2><p className="mt-2 text-sm leading-6 text-slate-600">Availability, timing, and final cost are confirmed only after the brief and dependencies are reviewed.</p></div></aside><ProposalForm initialService={service} initialExpert={expert} /></div></Container></section></main>;
}
