-- GeekyAce Digital Hub v3.2.0 data foundation.
-- PostgreSQL only. Review and back up the production database before applying.
-- This file is intentionally not executed by the application build.

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '2min';

ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "slug" TEXT;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "headline" TEXT;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "studioId" TEXT;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "yearsExperience" INTEGER;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "languages" TEXT;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "portfolioUrl" TEXT;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "featured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TeamMember" ADD COLUMN IF NOT EXISTS "published" BOOLEAN NOT NULL DEFAULT true;

CREATE UNIQUE INDEX IF NOT EXISTS "TeamMember_slug_key" ON "TeamMember"("slug");
CREATE INDEX IF NOT EXISTS "TeamMember_studioId_published_idx" ON "TeamMember"("studioId", "published");

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "source" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "serviceSlug" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "studioId" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "referrer" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "consent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "attachments" TEXT;

CREATE INDEX IF NOT EXISTS "Lead_status_createdAt_idx" ON "Lead"("status", "createdAt");
CREATE INDEX IF NOT EXISTS "Lead_source_idx" ON "Lead"("source");

CREATE TABLE IF NOT EXISTS "AceMatchBrief" (
  "id" TEXT NOT NULL,
  "goal" TEXT NOT NULL,
  "studioId" TEXT NOT NULL,
  "serviceSlug" TEXT,
  "audience" TEXT NOT NULL,
  "stage" TEXT NOT NULL,
  "timeline" TEXT NOT NULL,
  "budget" TEXT NOT NULL,
  "context" TEXT NOT NULL,
  "recommendedRoles" TEXT NOT NULL,
  "recommendedPhases" TEXT NOT NULL,
  "recommendedDeliverables" TEXT NOT NULL,
  "source" TEXT NOT NULL DEFAULT 'WEBSITE',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "leadId" TEXT,
  CONSTRAINT "AceMatchBrief_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "AceMatchBrief_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "AceMatchBrief_leadId_key" ON "AceMatchBrief"("leadId");
CREATE INDEX IF NOT EXISTS "AceMatchBrief_studioId_createdAt_idx" ON "AceMatchBrief"("studioId", "createdAt");
CREATE INDEX IF NOT EXISTS "AceMatchBrief_serviceSlug_idx" ON "AceMatchBrief"("serviceSlug");

CREATE TABLE IF NOT EXISTS "CaseStudy" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "summary" TEXT NOT NULL,
  "challenge" TEXT NOT NULL,
  "approach" TEXT NOT NULL,
  "outcome" TEXT NOT NULL,
  "studioId" TEXT NOT NULL,
  "serviceSlugs" TEXT NOT NULL,
  "industries" TEXT NOT NULL,
  "heroImageUrl" TEXT,
  "mediaUrls" TEXT,
  "proofStatus" TEXT NOT NULL DEFAULT 'CONCEPT',
  "proofUrl" TEXT,
  "clientPermission" BOOLEAN NOT NULL DEFAULT false,
  "clientDisplayName" TEXT,
  "featured" BOOLEAN NOT NULL DEFAULT false,
  "published" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CaseStudy_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "CaseStudy_slug_key" ON "CaseStudy"("slug");
CREATE INDEX IF NOT EXISTS "CaseStudy_published_featured_idx" ON "CaseStudy"("published", "featured");
CREATE INDEX IF NOT EXISTS "CaseStudy_studioId_proofStatus_idx" ON "CaseStudy"("studioId", "proofStatus");

-- Client workspace tables. Password hashes must be generated by the approved
-- authentication workflow; never insert plaintext passwords.
CREATE TABLE IF NOT EXISTS "Client" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "company" TEXT,
  "phone" TEXT,
  "passwordHash" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'ACTIVE',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Client_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "Client_email_key" ON "Client"("email");

CREATE TABLE IF NOT EXISTS "Project" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "status" TEXT NOT NULL DEFAULT 'PLANNING',
  "progress" INTEGER NOT NULL DEFAULT 0,
  "startDate" TIMESTAMP(3),
  "dueDate" TIMESTAMP(3),
  "budget" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "clientId" TEXT NOT NULL,
  CONSTRAINT "Project_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Project_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "Project_clientId_status_idx" ON "Project"("clientId", "status");

CREATE TABLE IF NOT EXISTS "ProjectMilestone" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "status" TEXT NOT NULL DEFAULT 'PENDING',
  "dueDate" TIMESTAMP(3),
  "completedAt" TIMESTAMP(3),
  "order" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "projectId" TEXT NOT NULL,
  CONSTRAINT "ProjectMilestone_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "ProjectMilestone_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "ProjectMilestone_projectId_order_idx" ON "ProjectMilestone"("projectId", "order");

CREATE TABLE IF NOT EXISTS "ProjectUpdate" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "projectId" TEXT NOT NULL,
  CONSTRAINT "ProjectUpdate_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "ProjectUpdate_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "ProjectUpdate_projectId_createdAt_idx" ON "ProjectUpdate"("projectId", "createdAt");

COMMIT;
